name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Clean previous builds
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Copy VC Runtime DLLs (fix possible white screen issues)
        shell: pwsh
        run: |
          Copy-Item "C:\Windows\System32\msvcp140.dll" "build/windows/x64/runner/Release\" -Force
          Copy-Item "C:\Windows\System32\vcruntime140.dll" "build/windows/x64/runner/Release\" -Force
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jbrc-windows
          path: build/windows/x64/runner/Release/
